### ISSUE TITLE
Recruit Usability Testers

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1072]
Recruit potential test subjects for upcoming sessions

**Comment by AlexJupiter** [comment]
Sent copy to Greta for approval: https://docs.google.com/document/d/17ijMWs5ISon_11c2nf_I0SR_NjIpvP4K6kvodLKGZgI/edit

**Comment by AlexJupiter** [comment]
Update:
- Greta has sent out copy to a variety of YLD contacts 
- Judit has recommended a couple of engineers from Conde Nast
- Casey has contacts from Joyent

Blocker: waiting for the product to be used without a client certificate or tunnel to test.

**Comment by AlexJupiter** [comment]
@AnthonyMann do you have any contacts that might be able to help us here?

**Comment by AlexJupiter** [comment]
Moving this to blocked, due to the difficulties in recruiting testers.

The avenues I have tried:
- Asking YLD marketing to [send out an email](https://docs.google.com/document/d/17ijMWs5ISon_11c2nf_I0SR_NjIpvP4K6kvodLKGZgI/edit) to meetup attendees
- Contacted previous external testers from CoPilot (at the time of comment I am still waiting on replies)

Next steps:
- [x] Send out Tweets from Joyent Product team personal accounts and Make Us Proud and YLD Twitter accounts. [Sample Tweet](https://twitter.com/AlexJupiter23/status/968736928010039296).
- [ ] Research external recruiting agencies. (@yaili any update on this?)

**Comment by AlexJupiter** [comment]
@yaili any update on using an external recruitment agency to get testers?

**Comment by AlexJupiter** [comment]
Thanks to @SaraVieira 's plugs I think we have some great leads for the next round. This will be an ongoing difficult task, however this can be closed for now.
