### ISSUE TITLE
Allow the ability to create an instance on IE11

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1088]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?
Any piece of functionality on the create instance page throws this error:
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/f409526c-82eb-47db-86ba-f16d6d57c541)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
View create instance in IE11

## What is the expected behavior?
A user should be able to accomplish all tasks on create instance in IE11

## What is the motivation / use case for changing the behavior?
A user should be able to accomplish all tasks on create instance in IE11

## If the current behavior is a bug, please provide your browser
IE11 on Windows 10

**Comment by ramitos** [comment]
fixed in:
- https://github.com/yldio/joyent-portal/commit/4760db95ffc259ffe19c1dc772b4f32df971ecc5
- https://github.com/yldio/joyent-portal/commit/0706548ed50c5da8b18ddf537628e0e492930e10
- https://github.com/yldio/joyent-portal/commit/7d02fb8777f0accdd6700150045ad1457b588d77
- https://github.com/yldio/joyent-portal/commit/0681fb05fecfdad1b4aea236a46a96b81bfdaecf
