### ISSUE TITLE
Choose tool of choice for analytics

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1237]
In line with the previously outlined data analytics goals, a tool (or tools) should be chosen to we can achieve those goals.

**Comment by AlexJupiter** [comment]
@SaraVieira and I had a session earlier where we analysed Heap Analytics. We concluded that it has promise, but feedback is needed from the rest of the team before progressing in this decision making process. 

To test out Google Analytics and Mixpanel it was concluded that a couple of days of engineering time would have to be dedicated to setting up the events and then more time using the product to reach a full conclusion on the each of the respective product's positive and negatives. 

It was believed that Mixpanel had a similar functionality to Heap Analytics (where one script is installed that records all events) however it looks like that feature has [been discontinued](https://help.mixpanel.com/hc/en-us/articles/115004598183-What-options-are-available-for-codeless-tracking-).

Instana was also researched, however from what we could deduce, it does not have the functionality required (specifically recording individual events) to make it a worthwhile contender. 

As we don't have a couple of days of engineering time to spare (to implement Google Analytics and/or Mixpanel), it would be great if everyone could use [Heap Analytics](https://heapanalytics.com) for about ten minutes and offer their individual feedback on the tool. From there we can continue to assess whether it's worth using more or not. I have sent out invites to everyone in the team to the live account, however do ask for a new invite if the old invite got lost in your inbox. 

(@hollowtf, @SaraVieira, @ramitos )

**Comment by misterbisson** [comment]
@AlexJupiter whatever we choose, we need to assume that Google Analytics will be part of the mix. The marketing team insists on it.

Also, I believe the codeless tracking feature of Mixpanel was discontinued because of the security implications, a factor that should make us cautious about using similar features from competing offerings.

**Comment by AlexJupiter** [comment]
@misterbisson in regards to Google Analytics, do you know what insights the marketing team would be expecting? When we implement Google Analytics it would be useful to understand their goals and motivations from the tool so we can implement it in the correct manner. 

That's an interesting insight in regards to the codeless tracking feature of Mixpanel. Heap do have [sensitive data best practices](https://docs.heapanalytics.com/docs/privacy-security). However, if we have to concern ourselves with the effort it would take to implement Heap in a compliant fashion, it does diminish the argument of it being more convenient and needing less of a manual setup.

**Comment by AlexJupiter** [comment]
@misterbisson do you know if the marketing team are also requesting Google Tag Manager, along with Google Analytics?

**Comment by fitzage** [comment]
Google Tag Manager is currently in use on joyent.com to allow adding and removing ad tracking/conversion code from other services without having to update the site (although we currently have some legacy tracking code that is embedded directly on the site).

As far as the current setup, we haven't implemented anything special like event tracking since the big analytics update broke the old even tracking methods, and it's been a low priority. But in regards to something like the portal, event tracking might be essential, since a lot of stuff happens within a single page, so the standard code probably wouldn't pick up on a lot of that. That being said, I'm not sure how much of that event data would actually be that useful from a marketing perspective.
