### ISSUE TITLE
Add Instance Management Descriptions on all tabs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1286]
Estimated at an 8, due to this being time consuming, and this being a joint engineering and design task.

**Comment by AlexJupiter** [comment]
View Figma files in instance management to close.

**Comment by AlexJupiter** [comment]
I think we are going to need to figure out a way to only show these descriptions if the user wants to see them. My concern at the moment is that these descriptions are going to clutter the page and be very annoying if a user keeps seeing them, and yet knows exactly what a feature does. 

I also think this problem is magnified on mobile. [Take CNS Management on mobile as an example ](https://www.figma.com/file/CUFh7KjVqdZHccrBVBpSnVdn/IM-CNS-DNS?node-id=68%3A2053), if the user is coming to this page to quickly find a CNS hostname, scrolling past this huge chunk of text is not going to be the best experience for them.

We've spoken about this before, and discussions lead to an info icon, that shows the description on hover. But this is only a potential solution and I think should be looked into more. @hollowtf what do you think?

**Comment by hollowtf** [comment]
I would not worry about clutter, there is a minimal amount of copy (often only 2 lines) and if given enough space then it shouldn't feel too busy. As for concerns about mobile, we have to remember that info icons work terribly on mobile due to the lack of the ability to 'hover' and the minimal clearance of 48px necessary to make something clickable on touch screens.

Creating a toggle to hide copy is, in my opinion, over engineering a problem that does not exist. Having users scroll on mobile is not an issues, it's part of the nature of having to view things on a narrow viewport. 

The question is instead whether copy is necessary on the IM tabs at all, I feel it adds a bit of context and for users, and visually provides a aspect of texture on a series of very flat screens. 

If you are still concerned, then I recommend looking at the mobile designs of a phone and see how they feel. You'll see that you can actually see the 2nd line of hostnames before the fold on an iPhone 8, which IMO is pretty good.

**Comment by AlexJupiter** [comment]
We can definitely do better than info icons, I agree, however I still do feel that this text at the top of every management tab, consistently like the way it is, is an annoyance. 

Note, Digital Ocean, GCP and AWS all employ some implementation of expanding/collapsing information components. GCP go even further with an "info panel": 
![image](https://user-images.githubusercontent.com/7900773/36988789-a4f5175c-2097-11e8-8339-e56d76b07866.png). Which I am not saying is the best solution, I just think each one of these products is solving this problem better than us at the moment. 

> The question is instead whether copy is necessary on the IM tabs at all
It definitely should be. It's the implementation I'm questioning here.

> Visually provides an aspect of texture on a series of very flat screens.
Can you elaborate on this?

> I recommend looking at the mobile designs of a phone
Yep, and there is so much text!! Now this is a _really_ rough wireframe, but what do you think?
![image](https://user-images.githubusercontent.com/7900773/36989079-907aa0b6-2098-11e8-9a34-d7cf6ab0a840.png)
When I was wireframing this I had a couple of things in mind:
- How can we show the interface to the user as quickly as possible, so they don't have to scroll and search
- An expandable/collapsing implementation of the info, would allow us to expand on the descriptions to appeal to more novice users (remembering Khang's comments here)
- The icon has just as much clearance as the copy to clipboard icons
