### ISSUE TITLE
Design flow for Create TSG 

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1327]
Design the end-to-end for creating a Service groups from the TSg list view.

**Comment by hollowtf** [comment]
Trying a new way of delivering design work. Here are the components and states of those componets:

Select template (https://www.figma.com/file/ZGa0NR6bhCmQjR5iMKQ2kVe3/TSGC-Select-Template?node-id=1%3A516)

Name & Instance count (https://www.figma.com/file/UTZbIbF5RwRKP2Cr3HSgS6Nz/TSGC-Name-and-Instance-count)

**Comment by AlexJupiter** [comment]
Looking for feedback from @misterbisson now.

**Comment by misterbisson** [comment]
Template selection looks solid. We need new help text, but that's a task for me.

I'm not clear: 

1. Instance prefix is a detail needed for the service group. Where should I see where that fits?
1. Service Groups have a name. I'm guessing that's elsewhere?

**Comment by misterbisson** [comment]
- Template selection in https://www.figma.com/file/ZGa0NR6bhCmQjR5iMKQ2kVe3/TSGC-Select-Template?node-id=1%3A516 looks solid
- I'm not sure it make sense to conjoin the service group name with the count of instances as shown in https://www.figma.com/file/UTZbIbF5RwRKP2Cr3HSgS6Nz/TSGC-Name-and-Instance-count
- We need an instance prefix that's not included here. 

Notes about instance count and instance name: the instance count will be edited frequently, but it's likely we need to make the instance prefix immutable.

**Comment by AlexJupiter** [comment]
> I'm not sure it make sense to conjoin the service group name with the count of instances
I've aligned all inputs in this form vertically now. [here:](https://www.figma.com/file/UTZbIbF5RwRKP2Cr3HSgS6Nz/TSG%3A-Name-%26-Instance-count?node-id=26%3A0). 
![image](https://user-images.githubusercontent.com/7900773/38251371-2fab9750-3749-11e8-9247-65d7ded0e57b.png)
Does this alleviate any concern?

An expanded tooltip version for the prefix is also [here:](https://www.figma.com/file/UTZbIbF5RwRKP2Cr3HSgS6Nz/TSG%3A-Name-%26-Instance-count?node-id=26%3A194). 
![image](https://user-images.githubusercontent.com/7900773/38251405-470556de-3749-11e8-8f0d-fc3f6e1c4cd9.png)

**Comment by misterbisson** [comment]
Upon review with the engineering team, we're realizing the instance prefix is actually quite problematic. Should the prefix be immutable? If not, what happens if the user changes it?

So, we started asking ourselves if we really needed it. As it turned out, we really weren't using it for much, and in thinking through how to explain it to users, we realized there were conditions in which user expectations might not match the limited use in the TSG. So, rather than have something that might create more user confusion than it solves and might create inconsistencies, we're thinking of cutting it.

Instead, we'll create instance names based on the service group ID/SHA1.

Let's say we have a service group named "my test service group". The SHA1 for that might be something like `991305fbccc6bccf68c2e730c70f373165d2b292` (this is generated by the TSG service when the new service group is added). If that service has three instances, they'll be named something like the following:

- `tsg-991305fb-86f7e437`
- `tsg-991305fb-e9d71f5e`
- `tsg-991305fb-84a51684`

**Comment by AlexJupiter** [comment]
I liked the fact that this prefix would be a good way for a user to filter TSG instances in the instance console, but because of the fact we are not showing the TSG instances in the instance console (yet), I think that what is proposed above is a good path forward. 

- [ ] I shall iterate on these designs with this new information.

**Comment by AlexJupiter** [comment]
> I'm not sure it make sense to conjoin the service group name with the count of instances

@misterbisson is your concern based on horizontal proximity, or due to the fact that are in the same section?

This approach is similar to the DO implementation for instance name and count.
