### ISSUE TITLE
Design Template flow additions

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1348]
Adjust the 'instance name' component to accommodate the template name and instance prefix. The rest of the template flow is exactly the same, except for the replacement of the naming component.

**Comment by hollowtf** [comment]
The redesigned component can be seen here: https://www.figma.com/file/Yh6U0d1pzjdacVtBCh418SF4/Template-Name

Any additions of revisions necessary, please let me now.

**Comment by AlexJupiter** [comment]
Very nice!

Questions:
1.) Doesn't it make sense for the prefix to be chosen before the name?
2.) These section titles are very long, if we were to have a verb in here (like on the new instance creation designs) then they would be even longer. For consistently, I think it does make sense to remove the verb from all section titles. Thoughts?

**Comment by misterbisson** [comment]
Clarification needed: is this the instance template creation workflow, or the service group creation workflow?

> Doesn't it make sense for the prefix to be chosen before the name?

If this is the instance template workflow, the instance prefix, as discussed in the workshops, is moving to the service group definition.

If this is the service group creation workflow, then there's some confusion about the difference between the service group name and the template name.

**Comment by AlexJupiter** [comment]
This is the instance template creation workflow. 

In regards to the instance prefix, the prefix does need to move to the service group definition and I shall update the designs to reflect this. 

I would like to confirm my understanding of the instance prefix and how this relates to instance deployment. Am I correct on the following statements?
- Once a TSG is created, with one new instance, a new instance will provision with a *different* instance name to the instance template. Yes?
- This new instance name, will be prepended with the TSG prefix. Yes?
- This new instance will appear in that user account's instance list. Yes?

Lastly, do all deployed instances, have an automatic template that will appear in the instance template list? I can see how this would be useful, however I cannot remember if we discussed otherwise.

**Comment by misterbisson** [comment]
> - a new instance will provision with a different instance name to the instance template. Yes?

Correct.

> - This new instance name, will be prepended with the TSG prefix. Yes?

Correct.

> - This new instance will appear in that user account's instance list. Yes?

Correct. Users with a TSG with 3 instances and a prefix of `mytesttsg` might see those three instances like this:

- `mytesttsg-86f7e437faa5a7fce15d1ddcb9eaeaea377667b8`
- `mytesttsg-e9d71f5ee7c92d6dc9e92ffdad17b8bd49418f98`
- `mytesttsg-84a516841ba77a5b4648de2cd0dfcb30ea46dbb4`

However, that discussion is about the service group, not the template.

> do all deployed instances, have an automatic template that will appear in the instance template list?

We discussed some of that, but not in detail. It's something we might want to do eventually, but not at this time. I'd like to avoid making dependencies between the consoles when the TSG service is new and untested.

**Comment by misterbisson** [comment]
Actually, see the notes in https://github.com/yldio/joyent-portal/issues/1327 about removing the instance prefix entirely.
