### ISSUE TITLE
Organise usability testing sessions for next sprint

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1368]
- [ ] Organise sessions for the first week of sprint 14.
- [ ] Request resources to assist with testing.
- [ ] Put together materials for testing

**Comment by AlexJupiter** [comment]
@misterbisson @heyawhite I am currently writing the [testing script](https://docs.google.com/document/d/1MRgBKICGxfSMPGv_kUDMgLxOj9f9U5FoAzUgg12Fu8Q/edit#heading=h.21j5flmem12t) and I'd really appreciate your input on the prompts for encouraging the participant to interact with the image console and the TSG console. For context, the participant will have already provisioned an instance in the session and we'll use the same script for that part as the last session.

**Image Console Prompt**
In regards to the instance you have just deployed, how would you save that configuration, so you could provision an instance with that exact same configuration at a later date?

**Triton Service Group Prompt**
I’d like you to imagine that you want to set up a Ghost blog on your account. You are a very famous person so you know you are going to need multiple Ghost instances at all times. How would you go about provisioning these multiple instances?

Do you both have any thoughts on the above?

**Comment by AlexJupiter** [comment]
> My big concern is that folks are not familiar with the concept of images.
I share this concern and I'm not sure how to communicate images in the testing sessions. Do we know what the equivalent would be on AWS?

> Is the concept of a "ghost blog" common?
We chose this example simply because there are Ghost blog infrastructure container images already loaded into Triton. This will of course not be immediately apparent, so perhaps this needs to be explained in more detail.

**Comment by heyawhite** [comment]
Working on a PR to better define images in our docs. In the meantime, testers may just not have the answer to the prompt. I think that's okay, as long as education is available on how it all works. I'll think about new copy for the portal on this topic as well.

And I never would have guessed that Ghost was a blogging platform, and honestly, I'm not sure how much that matters. The question is really about using TSG to scale, yes?

I think my suggestion above still works. We must be clearer as to the reason they would want multiple instances. If the instances have "ghost" in the name, using it may still work. Not being able to actually see it makes this sort of guesswork. That said, it's worth noting what the instances in the instance list _are_ because the only clue they have is the names (unless they spend time looking at the instance details).

**Comment by AlexJupiter** [comment]
> The question is really about using TSG to scale, yes?

Yep, that is what we are aiming for here.

If the participant is familiar with AMIs I also think we could draw that analogy with the explanation.

**Comment by AlexJupiter** [comment]
New notes template: https://docs.google.com/spreadsheets/d/1Kc48p6s8jUSZN_AGOLFwIoJBtyQQXpd_txH2yBWNwxQ/edit#gid=420033205
