### ISSUE TITLE
Navigation Tabs

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#157]
![screenshot from 2017-01-16 14-24-58](https://cloud.githubusercontent.com/assets/524382/21986514/a0a62fb4-dbf7-11e6-8efe-293d7baea599.png)

@ramitos I was thinking of making this component use:

```
<Styled.div``>
  <Ul>
    <Li>
      {{child}}
    </Li>
  </Ul>
</Styled.div>
```

And override the styles to look like:

![screenshot from 2017-01-16 14-28-51](https://cloud.githubusercontent.com/assets/524382/21986640/27187cf0-dbf8-11e6-9d6d-808cf06be34f.png)

**Comment by tomgco** [comment]
IE

```
<Tabs>
  <TabGroup>
    <OrganisationImage />
    <TabTitle>My dashboard</TabTitle>
  </TabGroup>
</Tabs>
```

**Comment by ramitos** [comment]
This way you would have to control the content visibility outside of the UI component, right? You're only displaying the tabs themselves.

Which seems like a perfectly reasonable choice, especially for our use case ;)

Our tabs are not really tabs because they only have one view, so I would go with that 👍

**Comment by tomgco** [comment]
I have a feeling that the name might change and might just be specific to the front-end.

**Comment by ramitos** [comment]
no longer relevant
