### ISSUE TITLE
Allow people to be view all logs of their application (limited scope)

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#188]
## Problem Statement
To be defined

## Persona
To be defined

## Latest Links (kept up to  date)
To be defined

**Comment by ajones5876** [comment]
**Workshop**
Activity feed/logs has been mentioned frequently in the past - from Casey, the team in general and also by users. 

Currently we can describe tham as:

1. scheduler logs = feed - any action from Triton and the portal. These can be caused by humans. 2. app logs = logs - Raw data from the application itself. 
(Also to consider: logging and the relationship to alerting)

The main thing here is to understand how we see them; 
- Are they the same thing? 
- Do they crossover? 
- What needs to go where? 
- How do they manifest within the platform? 

Log management for the complete application is possibly a more of a long term goal as this could (and most definately will) become very complicated. The worry is that within the current scope, we cannot produce something to such standard that users would rely on it rather than on a 3rd party service, such as Data Dog etc. 

Within this in mind (outcome from and based on our previous conversations with Casey), we will in the immediate term focus on the history of what has happened in the application; 
- Who? 
- When? 
- What?

This is the “Activity Feed”

The team here believe that this is the right way forward, but we should also try to help the user as much as we can - though we are not currently “providing this service”. 

Here is a list of things that we should aim for in regards to Logs:
- Is there a minimum set of tools for this that can be built by us? 
- We should make the effort to educate the user about Logs and tools they can use to get this function fully working. 
- Any education or info about logs, should be wherever a user would expect to find “Logs”-related items and we need to openly tell them how we “treat this”. 
- If we rely on a 3rd party provider, can we integrate it in such a way that the platform take you where you need to go? (from Joyent to Data Dog...) - Where an alert bring the user to a point where we can’t help them - “Show me this is Data Dog”
- What can possibly be done, is that we provide the Raw Data and then very explicitly educate/inform the user where to go from here/what to do
