### ISSUE TITLE
Allow users to visualise metrics (limited scope)

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#194]
## Problem Statement
A user will want to know the status/health of their services/instances. Metrics provide a way to do this.

## Persona
To be defined

## Latest Links (kept up to  date)
First mentioned in these meeting notes:
https://docs.google.com/a/yld.io/document/d/1ZDQVix9HVB05L5KV3OZ6AH6undQ9EGOP0Cr45HWfVsg/edit?usp=sharing
Workshop Sketches: https://drive.google.com/open?id=0Bw56g3tFwIuWcWtlTlNlb0JELUk
Visual Design: https://drive.google.com/file/d/0B1oWObk56wa5SDBlQ1Y1cTJuQWc/view?usp=sharing
Prototype: N/A
Technical Prototype: http://frontend.svc.f4b20699-b323-4452-9091-977895896da6.eu-ams-1.triton.zone:8000/biz-tech/projects/forest-foundation-dev/services/nginx/metrics
Test Results: N/A

**Comment by ajones5876** [comment]
@antonasdeduchovas visual designs: https://drive.google.com/file/d/0B1oWObk56wa5SDBlQ1Y1cTJuQWc/view?usp=sharing

**Comment by ajones5876** [comment]
**Technical Prototype**
@juditgreskovits: http://frontend.svc.f4b20699-b323-4452-9091-977895896da6.eu-ams-1.triton.zone:8000/biz-tech/projects/forest-foundation-dev/services/nginx/metrics

**Comment by ajones5876** [comment]
Video of integration of metrics with Prometheus:
https://joyent-portal.slack.com/files/alexjones/F437DLVEK/zoom_0.mp4

**Comment by ajones5876** [comment]
**Metrics Workshop**
Upon conclusion of our second round of testing it was noticed that our feedback in terms of the thumbnail metrics was inconclusive. We need to work out how to effectively test the technical prototype.

In light of this, our discussions concluded that we need to determine if the boxplot is fit for purpose. We will go about this by altering the testing session in two ways:
1.) By testing the 'learnability' of the boxplot. If after the user is shown an educational component (or the boxplot is explained by the session facilitator) and the user still doesn't understand what is being shown by the boxplot, then this means an alternative representation of the thumbnail metrics needs to be explored (to be completed by @ajones5876).
2.) By providing a flow in the testing narrative where analysing the metrics proves their purpose. A user needs to attempt to debug their application due to information presented in the metrics. This needs to be incorporated into testing whether boxplots are implemented or not. (to be completed by @ajones5876 and @juditgreskovits)

**Comment by ajones5876** [comment]
**Analysing Thumbnail Metrics Designs**
As outlined by @alex-windett:
![image](https://cloud.githubusercontent.com/assets/7900773/24901681/bc883ee4-1e9f-11e7-9a32-f70f5ffafc3a.png)

My questions: 
- what happens when a user hovers over?
- how can we get this updating quickly in the technical prototype to show something is happening?
- what are the scales going to be? And can these scales be changed?
- where does a user go when they click on the metric?
- what is the narrative we are going to use to test these metrics?
- how are we defining 'out of ordinary numbers'?
- showing six different graphs in an educational component is a great deal of information, can this be simplified? (see below)

![image](https://cloud.githubusercontent.com/assets/7900773/24905109/ad0176e2-1eaa-11e7-8538-af5d2a3112df.png)

**Comment by ajones5876** [comment]
**Metrics Workshop with @juditgreskovits**
- on hover the metrics should indicate instances (if possible with box plot) and also duration/scale

To Do:
- [ ] - Different colours for outliers and min/max values
- [ ] - Switching duration on large metrics, although we are limited to 3hrs with test data (15mins, 30mins, 1hr[default], 2hrs, 3hrs)
- [ ] - Scales need to be added to all metrics
- [ ] - A testing narrative needs to be decided: how would you figure out which instance isn't working? What would you say the health of your services are?

**Comment by ajones5876** [comment]
**New Designs**
After significant internal discussions the below educational component has be altered:

![image](https://cloud.githubusercontent.com/assets/7900773/24958682/0f335dac-1f88-11e7-8089-bd43dd26e2a6.png)

**Comment by ajones5876** [comment]
**Proposed Testing Narrative**

1. User lands on lists view and reads the educational component (above)
2. User is asked to determine the health of their Wordpress service (the user may click through to the large metrics)
3. User is asked to then determine which instance is malfunctioning in the Wordpress service
4. User will then click on the outlier taking them to the metrics for that particular instance
_5. User will then reprovision this instance, fixing the malfunction_ (@juditgreskovits / @ramitos is this the correct way to rectify this problem?)

**Comment by ajones5876** [comment]
**Workshop**
Purpose: to sketch possibilities for the interactions and visualisation of the large scale metrics

All notes and sketches in this drive folder: https://drive.google.com/open?id=0Bw56g3tFwIuWcWtlTlNlb0JELUk

Conclusions:
- a timeline makes the most sense to have at the top of the screen because it's persistent and streamlines the interactions with all metrics
- we should test three implementations of the graphs: line graphs, line graph box plots, box plots
