### ISSUE TITLE
Allow people to view the deployment queue of their services and understand the changes that have taken place in their application (Activity Feed)

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#220]
## Problem Statement
Users should be able to see the deployment queue of their services

## Persona
All

## Latest Links (kept up to  date)
- Workshop Sketches: https://drive.google.com/open?id=0Bw56g3tFwIuWM0JzZzBoZXpTUVE
- Visual Design: N/A
- Prototype: https://marvelapp.com/808hac9

**Comment by ajones5876** [comment]
**Workshop**
![image](https://cloud.githubusercontent.com/assets/7900773/22591814/65f483be-ea0e-11e6-8d78-519bde5e1235.png)

What level are we seeing the deployment queue? 
- The team believes that the project level is the most appropriate as that will automatically cover all levels.

What should be included in a deployment queue? 
- Scaling up and down
- Which service is changing
- Number of instances added or subtracted
- Data centres
- Progress of “states”
- Ability to stop/cancel - explicit and clear explanation of what happens if you do

When updating: add new before “removing” old ones.

**Comment by ajones5876** [comment]
**Workshop Sketches**
Workshop sketches are here: https://drive.google.com/open?id=0Bw56g3tFwIuWM0JzZzBoZXpTUVE

A key outcome was a general consensus to combine Activity Feed (https://github.com/yldio/joyent-portal/issues/190) with Deployment queue

**Comment by ajones5876** [comment]
**Prototype**
https://marvelapp.com/808hac9

**Comment by ajones5876** [comment]
@ramitos
