### ISSUE TITLE
Improve package selection designs relating to feedback from testing sessions

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#795]
Testing summary: https://docs.google.com/document/d/1eOt5rhdDAqWLDHqLyGZbA2dxyiLF_Jr4h7ewmFfKoW0/edit

**Comment by AlexJupiter** [comment]
I believe the ways to improve this (as a result of our internal discussions and testing notes above), are:
- display a list
- allow sorting (via price, GB Ram, vCPUs, Tb Disk)
- add names to packages (available via API and clearly visible in my.joyent)
- text input (to improve sliders)
- consistency between filtering with package types and SSD/Mag (perhaps checkboxes for both, or iconography could help)

**Comment by AlexJupiter** [comment]
- we also need to add education (however this is more of an overall improvement for instance creation)

**Comment by yaili** [comment]
This is a dev task so could be moved elsewhere:

- Scaling should correspond to actual values (need to estimate technical implementation here - this seems like a big task)

**Comment by AlexJupiter** [comment]
Table headings could be table sort

**Comment by yaili** [comment]
Here are some more designs:
- **[Table](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=20%3A267)**: included colourful icons, displays in list/table, added package names, changed sliders to text inputs with suggested values dropdown - this is mixing values right now, we'd have to think about that, disk type is just 1 checkbox
- **[Table headers](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=106%3A0)**: table headers are sortable, no icons, checkboxes for package types, table header is repeated top/bottom (prob needs some more visual differentiation from normal table rows)

Other notes:
- Normally digit-only table columns are aligned right and mixed/text-only columns are aligned left, because I added values to some of the columns and not to others, this looks a bit odd now, needs work
- Related to previous note, it's easy to understand what 3 GB is, instead of 0.003 TB, which we'd have to do if we decided to not mix units
- We'd need to define the behaviour of the sortable table columns, a common pattern is to have an indication that the column is sortable, e.g. ⬍ — and once you click on it you get either ⬆︎ or ⬇︎. Another way is to not show anything until you click and then you'd get either ⬆︎ or ⬇︎. Something that needs to be defined.

Any suggestions on what explore further?

**Comment by yaili** [comment]
- **[Checkboxes with icons](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=124%3A0)**: I've also made the table header a different background colour

**Comment by yaili** [comment]
Here is a good reference for table patterns: https://uxdesign.cc/design-better-data-tables-4ecc99d23356

**Comment by yaili** [comment]
Feedback to explore:
- [ ] Incorporate more icons within the content of the summary
- [ ] Tags more visual
- [ ] Remember to reorder
