### ISSUE TITLE
Add SSD and magnetic to package selection table

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#925]

**Comment by AlexJupiter** [comment]
@hollowtf could you document with this issue with links please so we can review and close?

**Comment by hollowtf** [comment]
In order to call out certain hard-drives as SSD, we used a Super Script label in the Disk size column. This super script label is set on a primary blue background to make it stand out.

Consensus amongst design is that this ticket is completed. 

https://www.figma.com/file/Mm72VDV9dljgjci40oQAOzKj/CI-Package-Table?node-id=253%3A387
