### ISSUE TITLE
Sticky footer for instance deployment

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#933]
From London sprint.

**Comment by hollowtf** [comment]
After exploration, it was concluded that stick footer was not appropriate to solve the problem of users not knowing they could skip certain parts f the CI journey.

It was reasoned that it added too many conflicting CTA and would increase propensity for error from confusion between 'Next' CTA and 'Deploy' CTA. 

Instead, a short term fix was designed. On the initial point of very optional section, the primary CTA should read 'Skip' instead of 'Next'.

The visual exploration for the stick footer can be found here: https://drive.google.com/drive/u/1/folders/1bcEKyzbmbTRA1KTOvORty0JFsEXeJaLf
