### ISSUE TITLE
Update Network Designs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#958]
Following a workshop with Casey, it's been realised that we need to include the appropriate information on the network designs.

**Comment by hollowtf** [comment]
I have adjusted the information presented in the Network cards to align with feedback from Casey.

Now open for review and feedback from others.

https://www.figma.com/file/ZTMvVu1oeHOVY67gtzAxRdAy/CI-Networks?node-id=5%3A1807

**Comment by yaili** [comment]
👍

**Comment by AlexJupiter** [comment]
@hollowtf a network does have an ID
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/5ce74681-ed8b-4d00-9361-ecd7a8310b0b)

However, I am unsure whether we need to display the long id, or the short id. @ramitos @SaraVieira any advice here?

**Comment by AlexJupiter** [comment]
Just so we don't lose sight of Yaili's comment in the figma file, as per Casey's instructions, the information we need to include about networks are: 
- Network ID
- Subnet
- IP range
- Provision a NAT zone (needs better label)
- Public
- Description

I also believe we need to include Network name

**Comment by AlexJupiter** [comment]
To close this off, I believe we just need to put whether the network has a NAT zone or not, and the network ID in the network information dropdown. 

I believe the current implementation highlights a NAT zone too much. In my opinion, I do not think it is that important.

**Comment by AlexJupiter** [comment]
Updated the designs: https://www.figma.com/file/ZTMvVu1oeHOVY67gtzAxRdAy/CI-Networks?node-id=174%3A12

@hollowtf I'm not convinced about the implementation of the NAT zone. Any ideas let me know.

**Comment by misterbisson** [comment]
More context for NAT zones:

These _only_ apply to fabric networks, not operator defined networks. SDC Public doesn't have one, for example, by "my fabric network," or whatever the default is called _does_.

The NAT zone is an implementation detail for a more general capability of supporting outbound public internet access. That is, an instance on that network can make requests out to the public internet, but stuff on the public internet can't make requests into the network. That's useful so that instances can reach out to update servers for `apt-get install thing` and such.

Without a NAT zone (or something providing similar capabilities), stuff on that network is even more isolated.

The label "provision a NAT zone" in the mock is probably incorrect because a NAT zone can't be provisioned at that time. It either is provisioned when the network is created or not.

There's a good reason to ask: do we want to focus on the NAT zone (the implementation detail) or outbound internet access (the capability)? Right now, everything in Triton uses the implementation detail, but the capability seems the more important thing to make clear.

**Comment by AlexJupiter** [comment]
@misterbisson thanks for the clarification. We've updated the [mock ups](https://www.figma.com/file/ZTMvVu1oeHOVY67gtzAxRdAy/CI-Networks?node-id=174%3A12) conveying the capability of a NAT zone as you highlighted. We can perhaps elaborate on the implementation when we turn to designing the creation and management of networks. 

The list of networks is now also alphabetised.

We've also updated the info for the Joyent-SDC networks to be "data center networks", and not "Fabric". The icon is a work in progress for now. 

As discussed in Slack, we will also update the description soon.
