### ISSUE TITLE
Add initial accordion next step animation to instance creation

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#995]
This animation is needed to make the interaction as a continuous one-page form easier to understand.

We can iterate and perfect this.

**Comment by hollowtf** [comment]
## Some notes on the latest version of animations

• Sections currently appear to scale it's height from 0% to 100%, creating the look that the section was squashed and is now bouncing back to it's original size.
• Instead of this, can we have it so that the section does not change its scale, but it's y-position changes instead. So the entire section is dropping from below it section title.
• Can we pair this with a soft fade in as well please.

**Comment by AlexJupiter** [comment]
In regards to this, I can't QA this properly because of this error: 
![image](https://user-images.githubusercontent.com/7900773/35336697-270fc7ba-0111-11e8-8c01-e91a1e363b52.png)

**Comment by ramitos** [comment]
@AlexJupiter you can use the branch `demo1`

**Comment by AlexJupiter** [comment]
- [ ] When going to next section, auto-scroll so section title sits at top of page

**Comment by ramitos** [comment]
fixed by https://github.com/yldio/joyent-portal/commit/89bddf5c3f083452ce7b9418a0d700f54b130ad0
